### PR TITLE
Add caching logic to listing for yarn runner

### PR DESCRIPTION
**Pull request by aaronabf**
Will add tests shortly.

### CODE REVIEW

**Comment by gregsterin** [comment]
looks good, but no test coverage for new functions. Can we add.

Also what happens if a cached cluster is terminated and still in the cache? Will we still do a describe cluster to see its real time state?

**Comment by aaronabf** [comment]
> looks good, but no test coverage for new functions

Yes. I intend to add tests later today.

> what happens if a cached cluster is terminated and still in the cache?

So I thought a lot about the new cluster and terminated cases. The former isn't a real problem since the pool wait loop will eventually find the cluster. There is an issue towards the end of the pool wait time but this isn't a frequent situation, and would only result in an extra cluster. The latter case of terminated clusters is subtler and trickier. Luckily when we list clusters we get their state. Therefore we only put entries back into the cache if they have a waiting/running state. This means that a terminated cluster can only be in the cache up to our frequency check time (30 seconds). In this case, in the yarn runner, querying the yarn api will fail and skip over the cluster. Therefore this situation should be ok.

**Comment by gregsterin** [comment]
Thanks for the description, great reasons.. Would be helpful to have the reasoning in the comment for the cache so its not forgotten.

**Comment by aaronabf** [comment]
Added lots of tests!

**Pull request merged**
